import path from "node:path";

const MIME_MAP: Record<string, string> = {
	".md": "text/markdown; charset=utf-8",
	".markdown": "text/markdown; charset=utf-8",
	".txt": "text/plain; charset=utf-8",
	".json": "application/json; charset=utf-8",
	".jsonc": "application/json; charset=utf-8",
	".ts": "text/typescript; charset=utf-8",
	".tsx": "text/typescript; charset=utf-8",
	".mts": "text/typescript; charset=utf-8",
	".js": "text/javascript; charset=utf-8",
	".jsx": "text/javascript; charset=utf-8",
	".mjs": "text/javascript; charset=utf-8",
	".html": "text/html; charset=utf-8",
	".htm": "text/html; charset=utf-8",
	".css": "text/css; charset=utf-8",
	".yaml": "text/yaml; charset=utf-8",
	".yml": "text/yaml; charset=utf-8",
	".toml": "text/toml; charset=utf-8",
	".xml": "application/xml; charset=utf-8",
	".svg": "image/svg+xml",
	".png": "image/png",
	".jpg": "image/jpeg",
	".jpeg": "image/jpeg",
	".gif": "image/gif",
	".webp": "image/webp",
	".avif": "image/avif",
	".ico": "image/x-icon",
	".bmp": "image/bmp",
	".pdf": "application/pdf",
	".zip": "application/zip",
	".tar": "application/x-tar",
	".gz": "application/gzip",
	".py": "text/x-python; charset=utf-8",
	".rs": "text/x-rustsrc; charset=utf-8",
	".go": "text/x-go; charset=utf-8",
	".sh": "text/x-shellscript; charset=utf-8",
	".csv": "text/csv; charset=utf-8",
	".tsv": "text/tab-separated-values; charset=utf-8",
	".env": "text/plain; charset=utf-8",
	".log": "text/plain; charset=utf-8",
	".ini": "text/plain; charset=utf-8",
	".conf": "text/plain; charset=utf-8",
	".mmd": "text/plain; charset=utf-8",
	".ipynb": "application/json; charset=utf-8",
	".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	".pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
	".doc": "application/msword",
	".xls": "application/vnd.ms-excel",
	".ppt": "application/vnd.ms-powerpoint",
	".mp4": "video/mp4",
	".webm": "video/webm",
	".mov": "video/quicktime",
	".m4v": "video/mp4",
	".mp3": "audio/mpeg",
	".wav": "audio/wav",
	".ogg": "audio/ogg",
	".m4a": "audio/mp4",
	".aac": "audio/aac",
};

/** Best-effort MIME type for a file path, falling back to `application/octet-stream`. */
export function contentTypeForPath(filePath: string): string {
	const ext = path.extname(filePath).toLowerCase();
	return MIME_MAP[ext] ?? "application/octet-stream";
}
